version: '3.2'

services:
    api:
        image: webdevops/php-nginx:8.2
        restart: unless-stopped
        volumes:
            - ./:/app/
        ports:
            - "9999:80"
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        networks:
            - local
        depends_on:
            - db

    db:
        image: mysql:8.0.32
        restart: unless-stopped
        tty: true
        ports:
            - "33062:3306"
        environment:
            MYSQL_DATABASE: dentist
            MYSQL_USER: dentist
            MYSQL_PASSWORD: dentist
            MYSQL_ROOT_PASSWORD: dentist
        volumes:
            - ./db:/var/lib/mysql/
        networks:
            - local

networks:
    local:
        driver: bridge
